# Generated by Django 4.0.2 on 2022-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('a_answer', models.CharField(max_length=255)),
                ('b_answer', models.CharField(max_length=255)),
                ('c_answer', models.CharField(max_length=255)),
                ('d_answer', models.CharField(max_length=255)),
            ],
        ),
    ]
