# Generated by Django 4.0.2 on 2022-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_rename_test_kimyo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimyo',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='Media'),
        ),
    ]
